USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS ECOMMERCE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;


CREATE DATABASE IF NOT EXISTS ECOMMERCE;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE.ANALYST;

CREATE TABLE IF NOT EXISTS ECOMMERCE.ANALYST.CUSTOMERS (
    CustomerID INT,
    Age FLOAT,
    City VARCHAR(50),
    SignupDate VARCHAR(20),
    CustomerSegment VARCHAR(50)
);
CREATE TABLE IF NOT EXISTS ECOMMERCE.ANALYST.PRODUCTS (
    ProductID INT,
    ProductName VARCHAR(100),
    ProductCategory VARCHAR(50),
    UnitPrice FLOAT
);
CREATE TABLE IF NOT EXISTS ECOMMERCE.ANALYST.PAYMENTS (
    PaymentID INT,
    OrderID INT,
    PaymentDate VARCHAR(20),
    PaymentStatus VARCHAR(50)
);
CREATE TABLE IF NOT EXISTS ECOMMERCE.ANALYST.ORDERS (
    OrderID INT,
    CustomerID INT,
    ProductID INT,
    Quantity INT,
    OrderDate VARCHAR(20),
    Discount FLOAT,
    PaymentStatus VARCHAR(50),
    OrderStatus VARCHAR(30)
);