ALTER WAREHOUSE ECOMMERCE_WH RESUME;

USE DATABASE ECOMMERCE;

COPY INTO ECOMMERCE.ANALYST.CUSTOMERS
    FROM @S3_STAGE
    FILES = ('customers.csv');
COPY INTO ECOMMERCE.ANALYST.PRODUCTS
    FROM @S3_STAGE
    FILES = ('products.csv');
COPY INTO ECOMMERCE.ANALYST.ORDERS
    FROM @S3_STAGE
    FILES = ('orders.csv');
COPY INTO ECOMMERCE.ANALYST.PAYMENTS
    FROM  @S3_STAGE
    FILES = ('payments.csv');